spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3308/springboot-example?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

mybatis:
  type-aliases-package: com.animo.mybatis.entity
  mapper-locations: classpath:/mapper/*.xml