# DataSource Config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3308/upload?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

mybatis-plus:
  type-aliases-package: com.animo.upload.entity
  mapper-locations: classpath:/mapper/*.xml

uploadFile:
  location: /Users/liujinyong/Documents/taskFile/
  resourceHandler: /upload/**
